### PR TITLE
Add Rescience template and folder structure

### PR DESCRIPTION
**Pull request by RafaelNH**
Hi @arokem! Check up this pull request! I looked into the rescience submission guide and they already had some pandoc templates! I think we should use them! I will adapt them according to what you did on the last PR.

### CODE REVIEW

**Comment by arokem** [comment]
👍

**Comment by arokem** [comment]
I would merge this, if I had write access on this repo :smile:

**Comment by RafaelNH** [comment]
@arokem - I just gave you write access to the repo. However, do not merge this PR yet! I want to add the info in article.md to the template already in this PR. I will add the WIP label for now!

**Comment by arokem** [comment]
Ah yes - I see the WIP tag now. And I have a green button for the merge now too!

**Pull request merged**
